name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  regression-test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "latest"

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          
      - name: Get Versions
        id: versions
        run: |
          echo "vault=$(grep 'VAULT_VERSION=' .env.example | cut -d '=' -f 2)" >> $GITHUB_OUTPUT
          echo "python_hash=${{ hashFiles('requirements.txt') }}" >> $GITHUB_OUTPUT

      - name: Cache Virtual Environment
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.versions.outputs.python_hash }}

      - name: Cache Vault Binary
        id: cache-vault
        uses: actions/cache@v4
        with:
          path: ~/bin/vault
          key: vault-${{ runner.os }}-${{ steps.versions.outputs.vault }}

      - name: Download Vault Binary
        run: |
          mkdir -p ~/bin
          if [ ! -f ~/bin/vault ]; then
            VERSION=${{ steps.versions.outputs.vault }}
            echo "Installing Vault ${VERSION}"
            curl -sLo vault.zip "https://releases.hashicorp.com/vault/${VERSION}/vault_${VERSION}_linux_amd64.zip"
            unzip vault.zip vault
            mv vault ~/bin/
          fi
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Setup Environment and Lint
        run: |
          task prereqs
          task setup
          task lint

      - name: Start Services and Configure
        run: |
          task up
          task init
          task terraform:apply
          sleep 10

      - name: Run Tests
        run: |
          task test

      - name: Upgrade Vault to new version and re-run regression suite
        run: |
          export PATH=$PWD/.venv/bin:$PATH
          task vault:upgrade

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results
          path: |
            report.xml
            coverage.xml
            report.html
            coverage_html/

      